language: java
jdk:
  - oraclejdk8
  - openjdk8
cache:
  directories:
  - $HOME/.m2
addons:
  mariadb: '10.1'
before_script:
  - mysql -u root -e "CREATE DATABASE athena;"
  - mysql -u root -e "CREATE USER 'athena'@'localhost' IDENTIFIED BY 'ihavesecurityissues';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'athena'@'localhost';"
before_install:
- pip install --user codecov
after_success:
  - codecov
after_failure:
  "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"